const usServices = [
  { name: '*otro', price: 1000 },
  { name: '*hbp-mamaria-pelvica-renal', price: 720 },
  { name: '*hbp-pelvica', price: 360 },
  { name: '*hbp-pelvica-renal', price: 540 },
  { name: '*hbp-prostatica-renal', price: 540 },
  { name: '*hbp-renal', price: 360 },
  { name: '*hbp-renal-vesical', price: 540 },
  { name: '*pelvica-renal-vesical', price: 540 },
  { name: '*vesical-renal', price: 360 },
  { name: '4d (6-7 meses o 24-30 semanas)', price: 450 },
  { name: 'abdominal', price: 250 },
  { name: 'angiopower doppler de articulaciones', price: 350 },
  { name: 'cadera', price: 250 },
  { name: 'cerebro', price: 250 },
  { name: 'cervical', price: 250 },
  { name: 'codo', price: 250 },
  { name: 'cuello', price: 250 },
  { name: 'dedo', price: 250 },
  { name: 'doppler arterial 1 miembro', price: 450 },
  { name: 'doppler arterial 2 miembros', price: 700 },
  { name: 'doppler venoso 1 miembro', price: 450 },
  { name: 'doppler venoso 2 miembros', price: 700 },
  { name: 'doppler arterias renal', price: 400 },
  { name: 'doppler de articulaciones', price: 350 },
  { name: 'doppler de carotidas', price: 400 },
  { name: 'doppler de mamas', price: 350 },
  { name: 'doppler de rinon transplantado', price: 300 },
  { name: 'doppler de fistula de arteria venosa', price: 300 },
  { name: 'doppler escrotal o testicular', price: 350 },
  { name: 'doppler fetal', price: 350 },
  { name: 'doppler hepatico o esplenoportal', price: 450 },
  { name: 'doppler onstetrico o flujometria', price: 350 },
  { name: 'doppler renal', price: 400 },
  { name: 'doppler tiroides', price: 350 },
  { name: 'ecografia toracica', price: 250 },
  { name: 'escrotal (testiculos)', price: 300 },
  { name: 'esplenica (bazo)', price: 250 },
  { name: 'fistula', price: 250 },
  { name: 'ginecologica para seguimiento folicular', price: 400 },
  { name: 'ginecologico', price: 250 },
  { name: 'glandulas salivales', price: 250 },
  { name: 'gluteo', price: 250 },
  { name: 'hbp', price: 250 },
  { name: 'mamaria', price: 250 },
  { name: 'mano', price: 250 },
  { name: 'muneca', price: 250 },
  { name: 'muslo', price: 250 },
  { name: 'muslos', price: 500 },
  { name: 'musculoesqueletico', price: 250 },
  { name: 'obstetrica de rutina', price: 250 },
  { name: 'obstetrica estructural 1 transluc nucal', price: 250 },
  { name: 'obstetrica estructural 2 morfolog gral', price: 350 },
  { name: 'partes blandas', price: 250 },
  { name: 'pared abdominal', price: 250 },
  { name: 'pared toracica', price: 250 },
  { name: 'pelvico suprapubico', price: 250 },
  { name: 'pelvico', price: 250 },
  { name: 'pie', price: 250 },
  { name: 'pies', price: 360 },
  { name: 'planta de pie', price: 250 },
  { name: 'prostatica', price: 250 },
  { name: 'puncion de hematoma de pie', price: 300 },
  { name: 'rastreo abdominal', price: 300 },
  { name: 'region inginal', price: 250 },
  { name: 'region trocanterea 1', price: 250 },
  { name: 'region trocanterea bilateral', price: 360 },
  { name: 'renal', price: 250 },
  { name: 'rinon transplantado', price: 300 },
  { name: 'rodilla', price: 250 },
  { name: 'rodillas', price: 360 },
  { name: 'talon', price: 250 },
  { name: 'tendon de aquiles', price: 250 },
  { name: 'testiculos', price: 300 },
  { name: 'tiroides', price: 300 },
  { name: 'tobillo', price: 250 },
  { name: 'tobillos', price: 360 },
  { name: 'transfontanelar (cerebro)', price: 250 },
  { name: 'trasvaginal ginecologica', price: 250 },
  { name: 'umbilical', price: 250 },
  { name: 'vesical', price: 250 },
  { name: 'vias urinarias', price: 250 },
];

const densServices = [
  { name: 'cadera derecha y columna', price: 300 },
  { name: 'cadera derecha e izquierda y columna', price: 450 },
  { name: 'cuerpo entero', price: 1000 },
  { name: 'pan dental', price: 180 },
];

const mgServices = [
  { name: 'mamografia bilateral digital', price: 400 },
  { name: 'mamografia con protesis', price: 600 },
  { name: 'placa adicional', price: 150 },
];

const rxServices = [
  { name: 'antebrazo ap lat', price: 250 },
  { name: 'abdomen simple ap', price: 250 },
  { name: 'art acromio clavicular c/s carga', price: 350 },
  { name: 'atm-articulacion temporo mandibular', price: 400 },
  { name: 'axial 60', price: 250 },
  { name: 'axial 90', price: 250 },
  { name: 'axial 30 60', price: 400 },
  { name: 'axial 60 90', price: 400 },
  { name: 'brazo ap lat', price: 250 },
  { name: 'cadera axial', price: 250 },
  { name: 'caderas ap', price: 250 },
  { name: 'caderas ap y lat', price: 400 },
  { name: 'calcaneo lat axial', price: 250 },
  { name: 'calcaneos (talones) lat axial', price: 400 },
  { name: 'cavum', price: 300 },
  { name: 'cd rayos x', price: 50 },
  { name: 'cistografia miccional y relleno c/c', price: 1000 },
  { name: 'codo ap lat', price: 250 },
  { name: 'codos ap y lat', price: 400 },
  { name: 'colangiografia p/sonda o iv', price: 1000 },
  { name: 'colon por enema', price: 1000 },
  { name: 'columna cervical ap lat', price: 300 },
  { name: 'columna cervical oblicuas', price: 300 },
  { name: 'columna cervical ap lat oblicuas', price: 500 },
  { name: 'col cervical ap lat oblicuas y dinamicas', price: 750 },
  { name: 'columna dorso lumbar ap lat', price: 500 },
  { name: 'columna dorsal ap lat', price: 300 },
  { name: 'columna lumbar ap lat', price: 300 },
  { name: 'columna lumbar ap lat oblicuas', price: 500 },
  { name: 'columna lumbo sacra ap lat', price: 300 },
  { name: 'columna sacro coxigea ap lat', price: 300 },
  { name: 'coxis ap lat', price: 250 },
  { name: 'craneo ap lat', price: 350 },
  { name: 'cxe-colon por enema c/c', price: 850 },
  { name: 'dedo ap lat', price: 250 },
  { name: 'dorsoplanttal y lat con apoyo pie izq', price: 250 },
  { name: 'ercp', price: 600 },
  { name: 'escapula', price: 250 },
  { name: 'esternon ap lat', price: 350 },
  { name: 'esofagograma c/c', price: 850 },
  { name: 'femur ap lat', price: 250 },
  { name: 'fistulografia 2 miembros', price: 1000 },
  { name: 'hbp-abdomen simple', price: 250 },
  { name: 'hemitorax', price: 250 },
  { name: 'histero-histerosalpingografia', price: 1000 },
  { name: 'hombro ap', price: 250 },
  { name: 'hombros ap', price: 400 },
  { name: 'huesos propios de la nariz', price: 300 },
  { name: 'humero ap lat', price: 400 },
  { name: 'mano ap oblicua', price: 250 },
  { name: 'manos ap (edad osea)', price: 250 },
  { name: 'manos ap oblicuas', price: 400 },
  { name: 'maxilar inferior', price: 350 },
  { name: 'munieca ap lat', price: 250 },
  { name: 'pelvis ap', price: 250 },
  { name: 'pelvis radiometria un miembro', price: 400 },
  { name: 'pie ap lat', price: 250 },
  { name: 'pies ambos lat', price: 400 },
  { name: 'pie c/carga ap lat y obl comparativa', price: 450 },
  { name: 'pielografia ascendente', price: 800 },
  { name: 'pierna ap lat', price: 250 },
  { name: 'rodilla ap lat', price: 250 },
  { name: 'rodilla ap lat axial 45', price: 300 },
  { name: 'rodillas ap lat', price: 400 },
  { name: 'rodillas ap lat axiales 30 60 90', price: 800 },
  { name: 'rotula axial', price: 250 },
  { name: 'rotula axial 30 60 90 comparativa', price: 450 },
  { name: 'senos paranasales (spn)', price: 250 },
  { name: 'serie gastroduodenal', price: 1000 },
  { name: 'sialografia bilateral 1 glandula', price: 1000 },
  { name: 'spn senos paranasales', price: 300 },
  { name: 'test de farrel', price: 450 },
  { name: 'tobillo ap lat', price: 250 },
  { name: 'torax ap', price: 250 },
  { name: 'torax ap lat', price: 400 },
  { name: 'transito intestinal', price: 1000 },
  { name: 'uretografia retrograda', price: 650 },
  { name: 'urografia iv o pielografia', price: 1000 },
  { name: 'water', price: 250 },
];

const ctServices = [
  { name: 'abdomen bi trifasico', price: 3000 },
  { name: 'abdomen c/c', price: 2000 },
  { name: 'abdomen simple', price: 1400 },
  { name: 'abdomen y pelvis c/c', price: 3200 },
  { name: 'abdomen y pelvis torax', price: 4800 },
  { name: 'angio tc cerebro', price: 2000 },
  { name: 'angio tc torax o abdomen', price: 3000 },
  { name: 'angio y urotac', price: 4000 },
  { name: 'caderas tomografia', price: 1400 },
  { name: 'cada region musculoesqueletico', price: 1200 },
  { name: 'cd tomografia', price: 100 },
  { name: 'clavicula', price: 1800 },
  { name: 'colonografia', price: 2200 },
  { name: 'columna cervical', price: 1400 },
  { name: 'columna dorsal', price: 1400 },
  { name: 'columna lumbar', price: 1200 },
  { name: 'columna lumbo sacra', price: 1400 },
  { name: 'columna vertebral 1 region', price: 1200 },
  { name: 'columna vertebral c/c', price: 2000 },
  { name: 'copia de placa', price: 100 },
  { name: 'craneo c/c', price: 900 },
  { name: 'craneo s/c y c/c', price: 1000 },
  { name: 'craneo simple', price: 500 },
  { name: 'cuello tomografia', price: 1200 },
  { name: 'cuello c/c o parotidas', price: 2000 },
  { name: 'cuello y torax', price: 3000 },
  { name: 'encefalo', price: 500 },
  { name: 'encefalo c/c', price: 800 },
  { name: 'escanografia', price: 500 },
  { name: 'hipofisis c/c (silla turca)', price: 1800 },
  { name: 'macizo facial', price: 1200 },
  { name: 'macizo facial c/c', price: 1800 },
  { name: 'oidos', price: 1300 },
  { name: 'oidos c/c', price: 1700 },
  { name: 'orbitas', price: 1300 },
  { name: 'orbitas c/c', price: 2000 },
  { name: 'partes blandas tomografia', price: 1300 },
  { name: 'pelvis', price: 1200 },
  { name: 'pelvis abdomen y torax c/c', price: 4600 },
  { name: 'pelvis c/c', price: 1800 },
  { name: 'pielo tac', price: 1500 },
  { name: 'pilotac y urotac (para transplante)', price: 4000 },
  { name: 'region musculoesqueletico', price: 1200 },
  { name: 'rodilla', price: 1300 },
  { name: 'spn-senos c/c', price: 1900 },
  { name: 'spn-senos paranasales 2 planos', price: 1300 },
  { name: 'torax alta resolucion', price: 1200 },
  { name: 'torax c/c', price: 1800 },
  { name: 'torax y craneo c/c', price: 2600 },
  { name: 'torax protocolo nodulo pulmonar', price: 1800 },
  { name: 'torax protocolo tep', price: 2800 },
  { name: 'torax simple', price: 1300 },
  { name: 'trifacico hbp c/c', price: 3200 },
  { name: 'urotac', price: 3200 },
];

module.exports = {
  usServices,
  densServices,
  mgServices,
  rxServices,
  ctServices,
};
